---
title: "Fig_1_Analysis"
author: "MD"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries

```{r}
library(readxl)
library(ggplot2)
library(cowplot)
library(maps)
library(ggmap)
library(knitr)
library(tidyverse)
library(plyr)
library(phyloseq)
library(tibble)
library(lme4)
library(Matrix)
library(reshape2)
library(ape)
library(mia)#needed for convertFromPhyloseq function (L266)
library(DESeq2) #needed for DESeqDataSetFromMatrix function (L277)
library(cowplot) #needed for plot agglomeration


library(car)
library(emmeans)
library(agricolae)
library(vegan)
library(pairwiseAdonis)
```

# Map

```{r}

#plot map of 10 farms
#site_locations<- read.csv("C:/Users/AG-PLP-cclabuser/Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis/Community_sequencing_data_analysis/Bloom_SiteLocations.csv")
#site_locations <- read.csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Bloom_SiteLocations.csv")
site_locations <- read.csv("Data/Bloom_SiteLocations.csv")
site_locations$Participant.ID <- as.factor(site_locations$Participant.ID)

# load United States state map data
new_york <- map_data("county")
new_york<- new_york[new_york$region == "new york",]

ggplot() + 
  geom_polygon( data=new_york, aes(x=long, y=lat, group = group),
                fill="lightblue" ) +
  geom_point(data = site_locations, size = 5, aes(x=Longitude, y=Latitude))

compost_locations <- site_locations[
  site_locations$Participant.ID =="132" |
    site_locations$Participant.ID =="118"|
    site_locations$Participant.ID =="156"|
    site_locations$Participant.ID =="172"|
    site_locations$Participant.ID =="21"|
    site_locations$Participant.ID =="213"|
    site_locations$Participant.ID =="223"|
    site_locations$Participant.ID =="226"|
    site_locations$Participant.ID =="232"|
    site_locations$Participant.ID =="244",]

map <- ggplot() + 
  geom_polygon( data=new_york, aes(x=long, y=lat, group = group),
                fill="lightblue" ) +
  geom_point(data = compost_locations, size = 5, aes(x=Longitude, y=Latitude, color = Participant.ID)) +
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));map

compost_locations$Num <- c("1","2","3","4","5","6","7","8","9","10")

map_together <- ggplot()+
  geom_polygon( data=new_york, aes(x=long, y=lat, group = group),
                fill="lightblue" ) +
  geom_point(data = site_locations, size = 5, aes(x=Longitude, y=Latitude))+
  geom_point(data = compost_locations, size = 5, aes(x=Longitude, y=Latitude, color = Participant.ID)) +
  geom_text(data = compost_locations, size = 5, label=compost_locations$Num,aes(x=Longitude-0.1, y=Latitude+0.1, color = Participant.ID)) +
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));map_together

#plot map and diversity plots together
map <- plot_grid(map, labels = "A", label_size = 20);map
```



# Alpha diveristy 

## Read in data 
```{r}
data <- read_excel("Data/Formatted data on samples used in analysis.xlsx",sheet="Data")
data$combined <- paste(data$`Participant Number`,data$B.E_10_Compost)
data$`Participant Number`<- as.factor(data$`Participant Number`)
data$combined <- as.factor(data$combined)
data$B.E_10_Compost <- as.factor(data$B.E_10_Compost)

par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))

sha.long <- dplyr::select(data, c("Extracted ID", "Cleaned ID", "Sequenced ID", "Participant Number", "bac.shan", "fun.shan", "B.E_10_Compost")) %>% 
  pivot_longer(., cols = c(bac.shan,fun.shan), names_to = "Taxa", values_to = "Shannon")

otu.long <- dplyr::select(data, c("Extracted ID", "Cleaned ID", "Sequenced ID", "Participant Number", "bac.rich", "fun.rich", "B.E_10_Compost")) %>% 
  pivot_longer(., cols = c(bac.rich,fun.rich), names_to = "Taxa", values_to = "OTU_Rich")

sim.long <- dplyr::select(data, c("Extracted ID", "Cleaned ID", "Sequenced ID", "Participant Number", "bac.sim", "fun.sim", "B.E_10_Compost")) %>% 
  pivot_longer(., cols = c(bac.sim,fun.sim), names_to = "Taxa", values_to = "Simp")
```

## Diversity models

### Shannon model

```{r}
g2C <- glmmTMB(Shannon~B.E_10_Compost*Taxa, data=sha.long)
mod <- lm(Shannon ~ B.E_10_Compost*Taxa, data = sha.long)
plot(mod)

summary(g2C)
Anova(mod, Type = 3)

joint_tests(g2C)
emmeans(g2C, pairwise ~ B.E_10_Compost, p.adjust = "none")
emmeans(g2C, pairwise ~ Taxa, p.adjust = "none")
t <- HSD.test(mod, "Taxa");t
```

### OTU Richness
```{r}
g2C <- glmmTMB(OTU_Rich~B.E_10_Compost*Taxa, data=otu.long)
mod <- lm(OTU_Rich ~ B.E_10_Compost*Taxa, data = otu.long)
plot(mod)

summary(g2C)
Anova(mod, Type = 3)

joint_tests(g2C)
emmeans(g2C, pairwise ~ B.E_10_Compost, p.adjust = "none")
emmeans(g2C, pairwise ~ Taxa, p.adjust = "none")
t <- HSD.test(mod, "Taxa");t
```

### Simpsons 
```{r}
g2C <- glmmTMB(Simp~B.E_10_Compost*Taxa, data=sim.long)
mod <- lm(Simp ~ B.E_10_Compost*Taxa, data = sim.long)
plot(mod)

summary(g2C)
Anova(mod, Type = 3)

joint_tests(g2C)
emmeans(g2C, pairwise ~ B.E_10_Compost, p.adjust = "none")
emmeans(g2C, pairwise ~ Taxa, p.adjust = "none")
t <- HSD.test(mod, "Taxa");t
```




```{r}
mod <- lm(OTU_Rich ~ B.E_10_Compost*Taxa, data = otu.long)
plot(mod)
Anova(mod, type = 3)
t <- HSD.test(mod, "Taxa");t
t.test(sim.long$Simp~sim.long$Taxa,mu = 0,    var.equal = TRUE,   conf.level = 0.95)


mod <- lm(Simp ~ B.E_10_Compost*Taxa, data = sim.long)
plot(mod)
Anova(mod, type = 3)
t <- HSD.test(mod, "Taxa");t
t.test(otu.long$OTU_Rich~otu.long$Taxa,mu = 0,    var.equal = TRUE,   conf.level = 0.95)

```
 
## T test

```{r}
bac.shan <- dplyr::select(data, c("Participant Number", "bac.shan", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "bac.shan")
t.test(bac.shan$`0`, bac.shan$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)

fun.shan <- dplyr::select(data, c("Participant Number", "fun.shan", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "fun.shan")
t.test(fun.shan$`0`, fun.shan$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)


bac.sim <- dplyr::select(data, c("Participant Number", "bac.sim", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "bac.sim")
t.test(bac.sim$`0`, bac.sim$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)

fun.sim <- dplyr::select(data, c("Participant Number", "fun.sim", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "fun.sim")
t.test(fun.sim$`0`, fun.sim$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)


bac.rich <- dplyr::select(data, c("Participant Number", "bac.rich", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "bac.rich")
t.test(bac.rich$`0`, bac.rich$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)

fun.rich <- dplyr::select(data, c("Participant Number", "fun.rich", "B.E_10_Compost")) %>% 
  pivot_wider(., names_from = "B.E_10_Compost", values_from = "fun.rich")
t.test(fun.rich$`0`, fun.rich$`1`,
    mu = 0,  paired = TRUE,   var.equal = TRUE,   conf.level = 0.95)
```


```{r}
P.bac <- readRDS("Data/output/P.field.bac.RDS")
P.fun <- readRDS("Data/output/P.field.fun.RDS")

dist = phyloseq::distance(P.bac, method="bray")
ordination = ordinate(P.bac, method="PCoA", distance=dist)
plot_ordination(P.bac, ordination, color="Participant.ID") + theme(aspect.ratio=1)

beta_bac <- ggplot(data = pca_scores_blf, aes(x=PC1,y=PC2)) +
  geom_point(aes(color = farm,shape = compost, size = 5))+
  scale_shape_discrete(labels = c("No", "Yes")) +
  guides(size = "none", color = guide_legend(title = "Farm ID", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom"),
         shape = guide_legend(title = "Compost", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom",ncol=1))

s <- sample_data(P.bac)
pcadata <- ordinate(P.bac, method = "PCoA", distance = "bray") 
  scores(display = "sites") %>%
  as.data.frame() %>%
  rownames_to_column("IMR_label")
  left_join(s, by = "sample")


```


```{r}
#generate plots for bacterial and fungal alpha diversity metrics
bac_rich <- ggplot(data, aes(B.E_10_Compost,bac.rich)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Bacterial OTU Richness") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));bac_rich

bac_shan <- ggplot(data, aes(B.E_10_Compost,bac.shan)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Bacterial Shannon Diversity") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));bac_shan

bac_sim <- ggplot(data, aes(B.E_10_Compost,bac.sim)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Bacterial Simpsons Diversity") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));bac_sim

fun_rich <- ggplot(data, aes(B.E_10_Compost,fun.rich)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Fungal OTU Richness") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));fun_rich

fun_shan <- ggplot(data, aes(B.E_10_Compost,fun.shan)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Fungal Shannon Diversity") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));fun_shan

fun_sim <- ggplot(data, aes(B.E_10_Compost,fun.sim)) +
  geom_bar(stat = "summary", position = "dodge", fill = "lightblue") +
  geom_jitter(width = 0.1, height = 0, aes(color = `Participant Number`), size = 3) +
  geom_errorbar(stat = "summary", position = "dodge", width=0.4, alpha=0.9, linewidth=0.5) +
  xlab(label = "") +
  ylab(label = "Fungal Simpsons Diversity") +
  scale_x_discrete(labels=c('No Compost','Compost'))+
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"));fun_sim

#plot all plots together for supplemental figure
sup <- plot_grid(bac_rich,bac_shan,bac_sim,fun_rich,fun_shan,fun_sim, nrow = 2,ncol = 3,labels = "AUTO",label_size = 20);sup

#plots OTU rich figures with labels for figure 1
alpha <- plot_grid(bac_shan,fun_shan,nrow = 2, ncol = 1, labels = c("B","C"),label_size = 20);alpha
```


```{r}
#plot map of 10 farms
#site_locations<- read.csv("C:/Users/AG-PLP-cclabuser/Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis/Community_sequencing_data_analysis/Bloom_SiteLocations.csv")
#site_locations <- read.csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Bloom_SiteLocations.csv")
site_locations <- read.csv("Data/Bloom_SiteLocations.csv")
site_locations$Participant.ID <- as.factor(site_locations$Participant.ID)

# load United States state map data
new_york <- map_data("county")
new_york<- new_york[new_york$region == "new york",]

ggplot() + 
  geom_polygon( data=new_york, aes(x=long, y=lat, group = group),
                fill="lightblue" ) +
  geom_point(data = site_locations, size = 5, aes(x=Longitude, y=Latitude))

compost_locations <- site_locations[
  site_locations$Participant.ID =="132" |
    site_locations$Participant.ID =="118"|
    site_locations$Participant.ID =="156"|
    site_locations$Participant.ID =="172"|
    site_locations$Participant.ID =="21"|
    site_locations$Participant.ID =="213"|
    site_locations$Participant.ID =="223"|
    site_locations$Participant.ID =="226"|
    site_locations$Participant.ID =="232"|
    site_locations$Participant.ID =="244",]

map <- ggplot() + 
  geom_polygon( data=new_york, aes(x=long, y=lat, group = group),
                fill="lightblue" ) +
  geom_point(data = compost_locations, size = 5, aes(x=Longitude, y=Latitude, color = Participant.ID)) +
  theme(legend.position = "none", strip.text = element_text(size = 15, color = "black"), 
        axis.title = element_text(size = 15, color = "black"),
        axis.text = element_text(size = 12, color = "black"))

#plot map and diversity plots together
map <- plot_grid(map, labels = "A", label_size = 20)

##############plot NMDS of communities

###import OTU tables, tax tables, and sample info table csvs as dfs
#bacterial_otu_mat<- read_csv("/Users/cclabuser/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/Experimental analysis of short read data from Eli/Bloom_otu_table_Bac.csv",)
#fungal_otu_mat<- read_csv("/Users/cclabuser/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/Experimental analysis of short read data from Eli/Bloom_otu_table_Fun.csv",)
#bacterial_tax_mat<- read_csv("/Users/cclabuser/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/Experimental analysis of short read data from Eli/Bloom_taxonomy_table_Bac.csv",)
#fungal_tax_mat<- read_csv("/Users/cclabuser/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/Experimental analysis of short read data from Eli/Bloom_taxonomy_table_Fun.csv",)
#comb_samples_df <- read_csv("/Users/cclabuser/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/Experimental analysis of short read data from Eli/Bloom_sample_info.csv",)
#bacterial_otu_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_otu_table_Bac.csv",)
bacterial_otu_mat <- read.csv("Data/Bloom_otu_table_Bac.csv")
#fungal_otu_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_otu_table_Fun.csv",)
fungal_otu_mat <- read.csv("Data/Bloom_otu_table_Fun.csv")
#bacterial_tax_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_taxonomy_table_Bac.csv",)
bacterial_tax_mat <- read.csv("Data/Bloom_taxonomy_table_Bac.csv")
#fungal_tax_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_taxonomy_table_Fun.csv",)
fungal_tax_mat <- read.csv("Data/Bloom_taxonomy_table_Fun.csv")
#comb_samples_df <- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_sample_info.csv",)
comb_samples_df <- read.csv("Data/Bloom_sample_info.csv")

###converts relevant column to rownames to each object
#Commented out because there was no ..1 column. instead, the first column is X
# bacterial_otu_mat <- bacterial_otu_mat %>%
#   tibble::column_to_rownames("...1") 
# fungal_otu_mat <- fungal_otu_mat %>%
#   tibble::column_to_rownames("...1") 
# bacterial_tax_mat <- bacterial_tax_mat %>%
#   tibble::column_to_rownames("...1") 
# fungal_tax_mat <- fungal_tax_mat %>%
#   tibble::column_to_rownames("...1") 
# comb_samples_df <- comb_samples_df %>%
#   tibble::column_to_rownames("IMR.Label")
bacterial_otu_mat <- bacterial_otu_mat %>%
  tibble::column_to_rownames("X")
fungal_otu_mat <- fungal_otu_mat %>%
  tibble::column_to_rownames("X")
bacterial_tax_mat <- bacterial_tax_mat %>%
  tibble::column_to_rownames("X")
fungal_tax_mat <- fungal_tax_mat %>%
  tibble::column_to_rownames("X")
comb_samples_df <- comb_samples_df %>%
  tibble::column_to_rownames("IMR.Label")

###adds taxonomic prefixes to bacterial tax table
bacterial_tax_mat$Kingdom<-sub("^","k__",bacterial_tax_mat$Kingdom)
bacterial_tax_mat$Phylum<-sub("^","p__",bacterial_tax_mat$Phylum)
bacterial_tax_mat$Class<-sub("^","c__",bacterial_tax_mat$Class)
bacterial_tax_mat$Order<-sub("^","o__",bacterial_tax_mat$Order)
bacterial_tax_mat$Family<-sub("^","f__",bacterial_tax_mat$Family)
bacterial_tax_mat$Genus<-sub("^","g__",bacterial_tax_mat$Genus)
bacterial_tax_mat$Species<-sub("^","s__",bacterial_tax_mat$Species)

###makes a new df of OTU# and the deepest taxonomy alignment for each bacterial and fungal OTU (again, not the most elegant solution :)
bac_combined_tax <- if_else(bacterial_tax_mat$Species == "_","test_true",bacterial_tax_mat$Species, missing = bacterial_tax_mat$Genus)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Family)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Order)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Class)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Phylum)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Kingdom)
bac_combined_tax <- melt(data.frame(rownames(bacterial_tax_mat),bac_combined_tax))
colnames(bac_combined_tax) <- c("OTU", "taxon")
bac_combined_tax$sequence <- bacterial_tax_mat$sequence

fun_combined_tax <- if_else(fungal_tax_mat$Species == "_","test_true",fungal_tax_mat$Species, missing = fungal_tax_mat$Genus)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Family)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Order)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Class)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Phylum)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Kingdom)
fun_combined_tax <- melt(data.frame(rownames(fungal_tax_mat),fun_combined_tax))
colnames(fun_combined_tax) <- c("OTU", "taxon")
fun_combined_tax$sequence <- fungal_tax_mat$sequence

###converts Participant.ID, composting, and relevant biopesticides to factors
comb_samples_df$Participant.ID <- as.factor(comb_samples_df$Participant.ID)
comb_samples_df$B.E_10_Compost <- as.factor(comb_samples_df$B.E_10_Compost)

###adds a column to comb_samples_df to indicate unique sample ID
comb_samples_df$IMR_label <- rownames(comb_samples_df)

###converts otu tables and tax tables to matrices
bacterial_otu_mat <- as.matrix(bacterial_otu_mat)
fungal_otu_mat <- as.matrix(fungal_otu_mat)
bacterial_tax_mat <- as.matrix(bacterial_tax_mat)
fungal_tax_mat <- as.matrix(fungal_tax_mat)

###converts all bacterial tables to single bacterial_phyloseq object
OTU = otu_table(bacterial_otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(bacterial_tax_mat)
samples = sample_data(comb_samples_df)

bacterial_phyloseq <- phyloseq(OTU, TAX, samples)
bacterial_phyloseq

###converts all fungal tables to single fungal_phyloseq object
OTU = otu_table(fungal_otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(fungal_tax_mat)
samples = sample_data(comb_samples_df)

fungal_phyloseq <- phyloseq(OTU, TAX, samples)
fungal_phyloseq


###makes subset of bacterial and fungal samples for 20 paired composted/uncomposted sites
bac_compost_phyloseq <- subset_samples(bacterial_phyloseq, 
                                       Participant.ID =="132" |
                                         Participant.ID =="118"|
                                         Participant.ID =="156"|
                                         Participant.ID =="172"| 
                                         Participant.ID =="21"| 
                                         Participant.ID =="213"| 
                                         Participant.ID =="223"| 
                                         Participant.ID =="226"| 
                                         Participant.ID =="232"| 
                                         Participant.ID =="244")
sample_names(bac_compost_phyloseq)
fun_compost_phyloseq <- subset_samples(fungal_phyloseq, 
                                       Participant.ID =="132" | 
                                         Participant.ID =="118"| 
                                         Participant.ID =="156"| 
                                         Participant.ID =="172"| 
                                         Participant.ID =="21"| 
                                         Participant.ID =="213"| 
                                         Participant.ID =="223"| 
                                         Participant.ID =="226"| 
                                         Participant.ID =="232"| 
                                         Participant.ID =="244")
sample_names(fun_compost_phyloseq)

#generates OTU and taxdata from those phyloseq objects
#em_tse <- convertFromPhyloseq(bac_compost_phyloseq)
em_tse <- makeTreeSEFromPhyloseq(bac_compost_phyloseq) #above is commented out as defunct function

assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Create DESeq2 object with minimal formula (adjust as needed)
dds_em <- DESeqDataSetFromMatrix(countData = count_mat,
                                 colData = coldata,
                                 design = ~ 1)

#dds_em <- estimateSizeFactors(dds_em, type = "poscounts")

# Variance stabilizing transformation
dso_stab_em <- varianceStabilizingTransformation(dds_em, blind = TRUE, fitType = "parametric")
vst_mat_em <- assay(dso_stab_em)

#get a matrix of pc values
pca_res_em <- prcomp(t(vst_mat_em), center = TRUE, scale. = FALSE)


pca_scores <- pca_res_em$x[, 1:2]  # PC1 and PC2 per sample
pca_scores <- as.data.frame(pca_scores)
pca_scores$SEQUENCED_INV_NUMBER <- row.names(pca_scores)
blf.clus.align <- as.data.frame(cbind(colData(em_tse)$IMR_label,as.character(colData(em_tse)$B.E_10_Compost),as.character(colData(em_tse)$Participant.ID)))
colnames(blf.clus.align) <- c("SEQUENCED_INV_NUMBER","compost","farm")
pca_scores_blf <- merge(pca_scores,blf.clus.align,by="SEQUENCED_INV_NUMBER")

#plot
beta_bac <- ggplot(data = pca_scores_blf, aes(x=PC1,y=PC2)) +
  geom_point(aes(color = farm,shape = compost, size = 5))+
  scale_shape_discrete(labels = c("No", "Yes")) +
  guides(size = "none", color = guide_legend(title = "Farm ID", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom"),
         shape = guide_legend(title = "Compost", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom",ncol=1))

beta_bac

#generates OTU and taxdata from those phyloseq objects
#em_tse <- convertFromPhyloseq(fun_compost_phyloseq)
em_tse <- makeTreeSEFromPhyloseq(fun_compost_phyloseq) #convert is defunct funciton

assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Create DESeq2 object with minimal formula (adjust as needed)
dds_em <- DESeqDataSetFromMatrix(countData = count_mat,
                                 colData = coldata,
                                 design = ~ 1)
#dds_em <- estimateSizeFactors(dds_em, type = "poscounts")

# Variance stabilizing transformation
dso_stab_em <- varianceStabilizingTransformation(dds_em, blind = TRUE, fitType = "parametric")
vst_mat_em <- assay(dso_stab_em)

#get a matrix of pc values
pca_res_em <- prcomp(t(vst_mat_em), center = TRUE, scale. = FALSE)


pca_scores <- pca_res_em$x[, 1:2]  # PC1 and PC2 per sample
pca_scores <- as.data.frame(pca_scores)
pca_scores$SEQUENCED_INV_NUMBER <- row.names(pca_scores)
blf.clus.align <- as.data.frame(cbind(colData(em_tse)$IMR_label,as.character(colData(em_tse)$B.E_10_Compost),as.character(colData(em_tse)$Participant.ID)))
colnames(blf.clus.align) <- c("SEQUENCED_INV_NUMBER","compost","farm")
pca_scores_blf <- merge(pca_scores,blf.clus.align,by="SEQUENCED_INV_NUMBER")

#plot
beta_fun <- ggplot(data = pca_scores_blf, aes(x=PC1,y=PC2)) +
  geom_point(aes(color = farm, shape = compost, size = 5)) +
  theme(legend.position = "none")

beta_fun

beta <- plot_grid(beta_bac, beta_fun, ncol = 1, nrow = 2,labels = c("D","E"),label_size = 20, rel_heights = c(1.2,1))
beta

fig_1<- plot_grid(map,alpha,beta, nrow = 1,ncol = 3, rel_widths = c(2, 1, 1.5))
fig_1

setwd("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis")
ggsave(filename = "data/output/Figure_1_with_PCOA.svg", plot = fig_1,
       width = 18, height = 8, device = "svg")
ggsave(filename = "Supplemental_figure_1.svg", plot = sup,
       width = 11, height = 10, device = "svg")

write.csv(compost_locations,"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_map_figure_data.csv")
write.csv(data,"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_alpha_div_figure_data.csv")
write.csv(as.data.frame(tax_table(bac_compost_phyloseq)),"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_fungal_community_figure_tax_data.csv")
write.csv(as.data.frame(otu_table(bac_compost_phyloseq)),"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_fungal_community_figure_otu_data.csv")
write.csv(as.data.frame(tax_table(fun_compost_phyloseq)),"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_bacterial_community_figure_tax_data.csv")
write.csv(as.data.frame(otu_table(fun_compost_phyloseq)),"/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/formatted_bacterial_community_figure_otu_data.csv")

```


# Ordination
```{r}
data <- read_excel("Data/Formatted data on samples used in analysis.xlsx",sheet="Data")
data$combined <- paste(data$`Participant Number`,data$B.E_10_Compost)
data$`Participant Number`<- as.factor(data$`Participant Number`)
data$combined <- as.factor(data$combined)
data$B.E_10_Compost <- as.factor(data$B.E_10_Compost)


bacterial_otu_mat <- read.csv("Data/Bloom_otu_table_Bac.csv")
#fungal_otu_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_otu_table_Fun.csv",)
fungal_otu_mat <- read.csv("Data/Bloom_otu_table_Fun.csv")
#bacterial_tax_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_taxonomy_table_Bac.csv",)
bacterial_tax_mat <- read.csv("Data/Bloom_taxonomy_table_Bac.csv")
#fungal_tax_mat<- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_taxonomy_table_Fun.csv",)
fungal_tax_mat <- read.csv("Data/Bloom_taxonomy_table_Fun.csv")
#comb_samples_df <- read_csv("/Users/clare/Library/CloudStorage/Box-Box/Ethan_M/Projects/Composting Project/USDA survey soil analysis and map/Community_sequencing_data_analysis/Community Sequencing Data from Eli/Bloom_sample_info.csv",)
comb_samples_df <- read.csv("Data/Bloom_sample_info.csv")

###converts relevant column to rownames to each object
#Commented out because there was no ..1 column. instead, the first column is X
# bacterial_otu_mat <- bacterial_otu_mat %>%
#   tibble::column_to_rownames("...1") 
# fungal_otu_mat <- fungal_otu_mat %>%
#   tibble::column_to_rownames("...1") 
# bacterial_tax_mat <- bacterial_tax_mat %>%
#   tibble::column_to_rownames("...1") 
# fungal_tax_mat <- fungal_tax_mat %>%
#   tibble::column_to_rownames("...1") 
# comb_samples_df <- comb_samples_df %>%
#   tibble::column_to_rownames("IMR.Label")
bacterial_otu_mat <- bacterial_otu_mat %>%
  tibble::column_to_rownames("X")
fungal_otu_mat <- fungal_otu_mat %>%
  tibble::column_to_rownames("X")
bacterial_tax_mat <- bacterial_tax_mat %>%
  tibble::column_to_rownames("X")
fungal_tax_mat <- fungal_tax_mat %>%
  tibble::column_to_rownames("X")
comb_samples_df <- comb_samples_df %>%
  tibble::column_to_rownames("IMR.Label")

###adds taxonomic prefixes to bacterial tax table
bacterial_tax_mat$Kingdom<-sub("^","k__",bacterial_tax_mat$Kingdom)
bacterial_tax_mat$Phylum<-sub("^","p__",bacterial_tax_mat$Phylum)
bacterial_tax_mat$Class<-sub("^","c__",bacterial_tax_mat$Class)
bacterial_tax_mat$Order<-sub("^","o__",bacterial_tax_mat$Order)
bacterial_tax_mat$Family<-sub("^","f__",bacterial_tax_mat$Family)
bacterial_tax_mat$Genus<-sub("^","g__",bacterial_tax_mat$Genus)
bacterial_tax_mat$Species<-sub("^","s__",bacterial_tax_mat$Species)

###makes a new df of OTU# and the deepest taxonomy alignment for each bacterial and fungal OTU (again, not the most elegant solution :)
bac_combined_tax <- if_else(bacterial_tax_mat$Species == "_","test_true",bacterial_tax_mat$Species, missing = bacterial_tax_mat$Genus)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Family)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Order)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Class)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Phylum)
bac_combined_tax <- if_else(bac_combined_tax == "_","test_true",bac_combined_tax, missing = bacterial_tax_mat$Kingdom)
bac_combined_tax <- melt(data.frame(rownames(bacterial_tax_mat),bac_combined_tax))
colnames(bac_combined_tax) <- c("OTU", "taxon")
bac_combined_tax$sequence <- bacterial_tax_mat$sequence

fun_combined_tax <- if_else(fungal_tax_mat$Species == "_","test_true",fungal_tax_mat$Species, missing = fungal_tax_mat$Genus)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Family)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Order)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Class)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Phylum)
fun_combined_tax <- if_else(fun_combined_tax == "_","test_true",fun_combined_tax, missing = fungal_tax_mat$Kingdom)
fun_combined_tax <- melt(data.frame(rownames(fungal_tax_mat),fun_combined_tax))
colnames(fun_combined_tax) <- c("OTU", "taxon")
fun_combined_tax$sequence <- fungal_tax_mat$sequence

###converts Participant.ID, composting, and relevant biopesticides to factors
comb_samples_df$Participant.ID <- as.factor(comb_samples_df$Participant.ID)
comb_samples_df$B.E_10_Compost <- as.factor(comb_samples_df$B.E_10_Compost)

###adds a column to comb_samples_df to indicate unique sample ID
comb_samples_df$IMR_label <- rownames(comb_samples_df)

###converts otu tables and tax tables to matrices
bacterial_otu_mat <- as.matrix(bacterial_otu_mat)
fungal_otu_mat <- as.matrix(fungal_otu_mat)
bacterial_tax_mat <- as.matrix(bacterial_tax_mat)
fungal_tax_mat <- as.matrix(fungal_tax_mat)

###converts all bacterial tables to single bacterial_phyloseq object
OTU = otu_table(bacterial_otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(bacterial_tax_mat)
samples = sample_data(comb_samples_df)

bacterial_phyloseq <- phyloseq(OTU, TAX, samples)
bacterial_phyloseq

###converts all fungal tables to single fungal_phyloseq object
OTU = otu_table(fungal_otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(fungal_tax_mat)
samples = sample_data(comb_samples_df)

fungal_phyloseq <- phyloseq(OTU, TAX, samples)
fungal_phyloseq


###makes subset of bacterial and fungal samples for 20 paired composted/uncomposted sites
bac_compost_phyloseq <- subset_samples(bacterial_phyloseq, 
                                       Participant.ID =="132" |
                                         Participant.ID =="118"|
                                         Participant.ID =="156"|
                                         Participant.ID =="172"| 
                                         Participant.ID =="21"| 
                                         Participant.ID =="213"| 
                                         Participant.ID =="223"| 
                                         Participant.ID =="226"| 
                                         Participant.ID =="232"| 
                                         Participant.ID =="244")
sample_names(bac_compost_phyloseq)
fun_compost_phyloseq <- subset_samples(fungal_phyloseq, 
                                       Participant.ID =="132" | 
                                         Participant.ID =="118"| 
                                         Participant.ID =="156"| 
                                         Participant.ID =="172"| 
                                         Participant.ID =="21"| 
                                         Participant.ID =="213"| 
                                         Participant.ID =="223"| 
                                         Participant.ID =="226"| 
                                         Participant.ID =="232"| 
                                         Participant.ID =="244")
sample_names(fun_compost_phyloseq)

#generates OTU and taxdata from those phyloseq objects
#em_tse <- convertFromPhyloseq(bac_compost_phyloseq)
em_tse <- convertFromPhyloseq(bac_compost_phyloseq) #above is commented out as defunct function

assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Create DESeq2 object with minimal formula (adjust as needed)
dds_em <- DESeqDataSetFromMatrix(countData = count_mat,
                                 colData = coldata,
                                 design = ~ 1)

#dds_em <- estimateSizeFactors(dds_em, type = "poscounts")

# Variance stabilizing transformation
dso_stab_em <- varianceStabilizingTransformation(dds_em, blind = TRUE, fitType = "parametric")
vst_mat_em <- assay(dso_stab_em)

#get a matrix of pc values
pca_res_em <- prcomp(t(vst_mat_em), center = TRUE, scale. = FALSE)


pca_scores <- pca_res_em$x[, 1:2]  # PC1 and PC2 per sample
pca_scores <- as.data.frame(pca_scores)
pca_scores$SEQUENCED_INV_NUMBER <- row.names(pca_scores)
blf.clus.align <- as.data.frame(cbind(colData(em_tse)$IMR_label,as.character(colData(em_tse)$B.E_10_Compost),as.character(colData(em_tse)$Participant.ID)))
colnames(blf.clus.align) <- c("SEQUENCED_INV_NUMBER","compost","farm")
pca_scores_blf <- merge(pca_scores,blf.clus.align,by="SEQUENCED_INV_NUMBER")

#plot
beta_bac <- ggplot(data = pca_scores_blf, aes(x=PC1,y=PC2)) +
  geom_point(aes(color = farm,shape = compost, size = 5))+
  scale_shape_discrete(labels = c("No", "Yes")) +
  guides(size = "none", color = guide_legend(title = "Farm ID", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom"),
         shape = guide_legend(title = "Compost", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom",ncol=1))

beta_bac
```
## Bacteria
```{r}
P.bac.fig1.rel = transform_sample_counts(bac_compost_phyloseq, function(x) x / sum(x))

d <- data.frame(sample_data(P.bac.fig1.rel))
data <- data.frame(t(otu_table(P.bac.fig1.rel)))
data <- decostand(data, method='hellinger')
dist <- vegdist(data, method='bray')

```


```{r}
ord <- capscale(dist ~ Participant.ID*B.E_10_Compost, data=d)
sppscores(ord) <- data
wcmdscale(dist, eig = T)

#points <- scores(wcmdscale(dist,eig=T,k=2),tidy=T)


# Perform PCoA using cmdscale
pcoa_results <- cmdscale(dist, k = 2, eig = TRUE, add = TRUE) # `add=TRUE` handles negative eigenvalues
# Extract the PCoA positions (coordinates for the plot)
pcoa_positions <- as_tibble(pcoa_results$points)
colnames(pcoa_positions) <- c("PCoA1", "PCoA2") # Rename columns for clarity
points <- scores(pcoa_results)
points<- as.data.frame(points)
colnames(points) <- c("PCoA1", "PCoA2") # Rename columns for clarity
points$IMR_label <- rownames(points)


# Calculate the percentage of variation explained by each axis
eigenvalues <- pcoa_results$eig
percent_explained_PC1 <- round(100 * eigenvalues[1] / sum(eigenvalues), 1)
percent_explained_PC2 <- round(100 * eigenvalues[2] / sum(eigenvalues), 1)

# Combine the PCoA coordinates with sample metadata
# Ensure row names match between metadata and the original data
d <- data.frame(sample_data(P.bac.fig1.rel))
pcoa_data <- dplyr::inner_join(points,d, by = "IMR_label")

ggplot(pcoa_data, aes(x = PCoA1, y = PCoA2, color = Participant.ID, shape = B.E_10_Compost)) + # Color and shape by a metadata variable
  geom_point(size = 3) + # Adjust point size and transparency
  labs(
    x = paste("PCoA 1 (", percent_explained_PC1, "%)", sep = ""),
    y = paste("PCoA 2 (", percent_explained_PC2, "%)", sep = ""),
    title = "PCoA Plot with Bray-Curtis Distance"
  ) +
  theme_bw() + # Use a clean theme
  coord_fixed() # Ensures axes are scaled equally

beta_bac <- ggplot(data = pcoa_data, aes(x=PCoA1,y=PCoA2)) +
  geom_point(aes(color = Participant.ID,shape = B.E_10_Compost, size = 5))+
  scale_shape_discrete(labels = c("No", "Yes")) +
  labs(x = paste("PCoA 1 (", percent_explained_PC1, "%)", sep = ""),
    y = paste("PCoA 2 (", percent_explained_PC2, "%)", sep = "")) +
  guides(size = "none", color = guide_legend(title = "Farm ID", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom"),
         shape = guide_legend(title = "Compost", theme = theme(legend.title = element_text(size = 12), legend.text = element_text(size = 12)),position = "bottom",ncol=1));beta_bac
```

## Fungi
```{r}
P.fun.fig1.rel = transform_sample_counts(fun_compost_phyloseq, function(x) x / sum(x))

d <- data.frame(sample_data(P.fun.fig1.rel))
data <- data.frame(t(otu_table(P.fun.fig1.rel)))
data <- decostand(data, method='hellinger')
dist <- vegdist(data, method='bray')

```


```{r}
ord <- capscale(dist ~ Participant.ID*B.E_10_Compost, data=d)
sppscores(ord) <- data
wcmdscale(dist, eig = T)

#points <- scores(wcmdscale(dist,eig=T,k=2),tidy=T)


# Perform PCoA using cmdscale
pcoa_results <- cmdscale(dist, k = 2, eig = TRUE, add = TRUE) # `add=TRUE` handles negative eigenvalues
# Extract the PCoA positions (coordinates for the plot)
pcoa_positions <- as_tibble(pcoa_results$points)
colnames(pcoa_positions) <- c("PCoA1", "PCoA2") # Rename columns for clarity
points <- scores(pcoa_results)
points<- as.data.frame(points)
colnames(points) <- c("PCoA1", "PCoA2") # Rename columns for clarity
points$IMR_label <- rownames(points)


# Calculate the percentage of variation explained by each axis
eigenvalues <- pcoa_results$eig
percent_explained_PC1 <- round(100 * eigenvalues[1] / sum(eigenvalues), 1)
percent_explained_PC2 <- round(100 * eigenvalues[2] / sum(eigenvalues), 1)

# Combine the PCoA coordinates with sample metadata
# Ensure row names match between metadata and the original data
d <- data.frame(sample_data(P.fun.fig1.rel))
pcoa_data <- dplyr::inner_join(points,d, by = "IMR_label")

ggplot(pcoa_data, aes(x = PCoA1, y = PCoA2, color = Participant.ID, shape = B.E_10_Compost)) + # Color and shape by a metadata variable
  geom_point(size = 3) + # Adjust point size and transparency
  labs(
    x = paste("PCoA 1 (", percent_explained_PC1, "%)", sep = ""),
    y = paste("PCoA 2 (", percent_explained_PC2, "%)", sep = ""),
    title = "PCoA Plot with Bray-Curtis Distance"
  ) +
  theme_bw() + # Use a clean theme
  coord_fixed() # Ensures axes are scaled equally

beta_fun <- ggplot(data = pcoa_data, aes(x=PCoA1,y=PCoA2)) +
  geom_point(aes(color = Participant.ID,shape = B.E_10_Compost, size = 5))+
  scale_shape_discrete(labels = c("No", "Yes")) +
  labs(x = paste("PCoA 1 (", percent_explained_PC1, "%)", sep = ""),
    y = paste("PCoA 2 (", percent_explained_PC2, "%)", sep = ""))+
  theme(legend.position = "none");beta_fun
```

```{r}
beta <- plot_grid(beta_bac, beta_fun, ncol = 1, nrow = 2,labels = c("D","E"),label_size = 20, rel_heights = c(1.2,1));beta
```
# Together plot

```{r}
fig_1_pcoa<- plot_grid(map,alpha,beta, nrow = 1,ncol = 3, rel_widths = c(2, 1, 1.5));fig_1_pcoa
ggsave(filename = "Data/output/Figure_1_pcoa.svg", plot = fig_1_pcoa,
       width = 18, height = 8, device = "svg")
```



