---
title: "Beta_Disper"
author: "MD"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#########################
#Ordination. Updated version using microbiome clusters
#Updated on 9/22/25 for Revision 2.
#########################

#Loading of the packages
###########
library(mia)
library(patchwork)
library(tidySummarizedExperiment)
library(ALDEx2)
library(MicrobiomeStat)
library(knitr)
library(tidyverse)
library(ape)
library(paletteer)
library(microbiome)
library(TreeSummarizedExperiment)
library(DESeq2)
library(M3C)
library(vegan)
library(scales)
library(colorRamp2)
library(readxl)
library(cowplot)
library(glmmTMB)
library(pairwiseAdonis)
library(car)
library(emmeans)
###########
```

# Read in data 
```{r}

FUN <- read.csv("Data/EJM-CLS-22F_pct98.csv")
BAC <- read.csv("Data/EJM-CLS-22B_pct98.csv")
BAC <- BAC[!is.na(BAC$Kingdom),]
FUN <- FUN[FUN$Kingdom =="k__Fungi",]
FUN <- FUN[!is.na(FUN$Kingdom),]

SAMPLE_DATA <- as.data.frame(read_xlsx("Data/Sequencing_data_formatted_for_analysis(01.28.2026).xlsx", sheet = "Soil_sample_info"))

#converts "OTU" column to rownames for all objects
rownames(FUN) <- FUN$X
FUN <- FUN[,-1]
rownames(BAC) <- BAC$X
BAC <- BAC[,-1]

###adds taxonomic prefixes to bacterial tax tables
BAC$Kingdom<-sub("^","k__",BAC$Kingdom)
BAC$Kingdom<-sub("k__NA",NA,BAC$Kingdom)
BAC$Phylum<-sub("^","p__",BAC$Phylum)
BAC$Phylum<-sub("p__NA",NA,BAC$Phylum)
BAC$Class<-sub("^","c__",BAC$Class)
BAC$Class<-sub("c__NA",NA,BAC$Class)
BAC$Order<-sub("^","o__",BAC$Order)
BAC$Order<-sub("o__NA",NA,BAC$Order)
BAC$Family<-sub("^","f__",BAC$Family)
BAC$Family<-sub("f__NA",NA,BAC$Family)
BAC$Genus<-sub("^","g__",BAC$Genus)
BAC$Genus<-sub("g__NA",NA,BAC$Genus)
BAC$Species<-sub("^","s__",BAC$Species)
BAC$Species<-sub("s__NA",NA,BAC$Species)

###converts Participant.ID, composting, and relevant biopesticides to factors
SAMPLE_DATA$EJM_SOIL_NUMBER <- as.factor(SAMPLE_DATA$EJM_SOIL_NUMBER)

#########Generates well formated object for taxonomy, OTU abundance, and sample data
###converts otu tables and tax tables to matrices
FUN_OTU<- FUN[,8:length(colnames(FUN))]
FUN_TAX <- FUN[,1:7]
BAC_OTU<- BAC[,8:length(colnames(BAC))]
BAC_TAX <- BAC[,1:7]

#Removes OTUs with only 1 read in the whole dataset
BAC_OTU <- BAC_OTU[rowSums(BAC_OTU)>1,]
FUN_OTU <- FUN_OTU[rowSums(FUN_OTU)>1,]

#removes samples with less than 3000 reads
BAC_OTU <- BAC_OTU[,colSums(BAC_OTU)>1000]
FUN_OTU <- FUN_OTU[,colSums(FUN_OTU)>1000]

colSums(BAC_OTU)

###converts relevant column to rownames to each object
rownames(SAMPLE_DATA)<- SAMPLE_DATA$SEQUENCED_INV_NUMBER

#####Generates ordinations for each dataset

#BAC_FIELD
#################################################################
SAMPLE_DATA_FIELD <- SAMPLE_DATA[SAMPLE_DATA$SOIL_SOURCE=="FIELD",]
#limits otu table to only samples used in compost study
OTU <- BAC_OTU[,colnames(BAC_OTU) %in% rownames(SAMPLE_DATA_FIELD)]


#Removes OTUs absent from all relevant samples
OTU <- OTU[rowSums(OTU)>1,]
OTU <- as.matrix(OTU)
TAX = BAC_TAX[rownames(OTU),]
samples = SAMPLE_DATA_FIELD[colnames(OTU),]
sample_names(samples) <- samples$SEQUENCED_INV_NUMBER
rownames(samples) <- samples$SEQUENCED_INV_NUMBER
em_tse <- TreeSummarizedExperiment(assays = list(Count = OTU),
                                   rowData = TAX,
                                   colData = samples)
assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Create DESeq2 object with minimal formula (adjust as needed)
dds_em <- DESeqDataSetFromMatrix(countData = count_mat,
                                 colData = coldata,
                                 design = ~ 1)

#dds_em <- estimateSizeFactors(dds_em, type = "poscounts")

# Variance stabilizing transformation
dso_stab_em <- varianceStabilizingTransformation(dds_em, blind = TRUE, fitType = "parametric")
vst_mat_em <- assay(dso_stab_em)
```


# Bacteria 
```{r}
#####
#If field data is needed, see "MIcrobiomeOrdination_v4_EM.R"
#BAC_LAB
#################################################################
SAMPLE_DATA_LAB <- SAMPLE_DATA[SAMPLE_DATA$SOIL_SOURCE=="LAB",]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[!is.na(SAMPLE_DATA_LAB$Collection_Date),]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[SAMPLE_DATA_LAB$Collection_Date!="45777",]


#limits otu table to only samples used in compost study
OTU <- BAC_OTU[,colnames(BAC_OTU) %in% rownames(SAMPLE_DATA_LAB)]
#Removes OTUs absent from all relevant samples
OTU <- OTU[rowSums(OTU)> 1,]
#OTU <- OTU+1

rowSums(OTU)

OTU <- as.matrix(OTU)
TAX = BAC_TAX[rownames(OTU),]
samples = SAMPLE_DATA_LAB[colnames(OTU),]
sample_names(samples) <- samples$SEQUENCED_INV_NUMBER
rownames(samples) <- samples$SEQUENCED_INV_NUMBER
em_tse <- TreeSummarizedExperiment(assays = list(Count = OTU),
                                   rowData = TAX,
                                   colData = samples)
assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Adonis - Mary code
P.bac.fig3 <- convertToPhyloseq(em_tse,assay.type = "counts")
P.bac.fig3.rel = transform_sample_counts(P.bac.fig3, function(x) x / sum(x))
d <- data.frame(sample_data(P.bac.fig3.rel))
data <- data.frame(t(otu_table(P.bac.fig3.rel)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')
```

```{r}

# Beta dispersion
mod <- betadisper(dist, interaction(d$Slurry, d$Compost), type = c("centroid"),bias.adjust = F)
mod
par(mfrow=c(2,2))
plot(mod)
anova(mod)
plot(mod, ellipse = TRUE, hull = FALSE, conf = 0.90) # 90% data ellipse
(mod.HSD <- TukeyHSD(mod))
plot(mod.HSD)
boxplot(mod,
        xlab="Week")
print(mod, digits = max(3, getOption("digits") - 3),
                           neigen = 8)

df <- as.data.frame(mod$distances)
df$SEQUENCED_INV_NUMBER <- rownames(df)
names(df)[names(df) == "mod$distances"] <- "distance"



d.bd <- dplyr::inner_join(df, d, by = "SEQUENCED_INV_NUMBER")


mod <- lm(distance ~ Slurry*Compost, data = d.bd) 
plot(mod)
Anova(mod, type = 3)
emmip(mod, Compost ~ Slurry, CIs = TRUE)
res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
plot(res[[1]], horizontal=F)
df <- as.data.frame(emmeans(mod, ~ Compost*Slurry))

res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  dplyr::select(., Compost, Slurry, .group)
df <- dplyr::inner_join(df,groups, by = c('Compost', 'Slurry'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)


d.bd <- d.bd %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))

df <- df %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))

p.beta.bac <- ggplot() +
  geom_boxplot(data=d.bd, aes(x=Slurry, y=distance, fill = interaction(Compost, Slurry))) +
  labs(y="Distance to the Centroid")+
  theme_classic()+
  scale_color_manual(values = c("black", "black"),guide = "none")+
  scale_fill_manual(values = c("#EC7063","#B03A2E","#5DADE2","#21618C"),
                    labels=c('Crossroads No Compost', 'Crossroads With Compost', 'Remembrance No Compost', 'Remembrance With Compost')) +
  geom_text(data=df,stat='identity',
            aes(x=Slurry, y=emmean+SE+0.01, label=letters, color = Compost), 
            size=4,position=position_dodge(.9))+
  scale_x_discrete(labels = c("CROSS" = "Crossroads", "REM" = "Remembrance"))+
  theme(axis.text.x=element_text(colour = "black"),
        axis.text.y=element_text(colour = "black"),
        axis.title.x=element_blank(),
        legend.title = element_blank(),
        axis.line = element_line(colour = "black"));p.beta.bac

p.bac.beta <- ggplot(data=df,aes(x=Slurry, y=emmean, label=letters,fill = interaction(Compost, Slurry))) +
  geom_col(position = "dodge") +
  labs(y="Distance to the Centroid")+
  theme_classic()+  
   geom_errorbar(position = position_dodge(0.9),width=0.25,alpha=0.5, aes(ymin = emmean-SE, ymax = emmean+SE, group=interaction(Compost, Slurry),color=Compost))+
  scale_color_manual(values = c("black", "black"),guide = "none")+
  scale_fill_manual(values = c("#EC7063","#B03A2E","#5DADE2","#21618C"),
                    labels=c('Crossroads No Compost', 'Crossroads With Compost', 'Remembrance No Compost', 'Remembrance With Compost')) +
  geom_text(aes(y=emmean+SE, label=letters, color = Compost,hjust =-2,vjust=1), 
            size=4,position=position_dodge(.9))+
  scale_x_discrete(labels = c("CROSS" = "Crossroads", "REM" = "Remembrance"))+
  theme(axis.text.x=element_text(colour = "black"),
        axis.text.y=element_text(colour = "black"),
        axis.title.x=element_blank(),
        legend.title = element_blank(),
        legend.position="none",
        axis.line = element_line(colour = "black"));p.bac.beta

fill_colors = c("#EC7063","#B03A2E","#5DADE2","#21618C")

p.bac.beta <- ggplot(data=df,aes(x=Slurry, y=emmean, label=letters,fill = interaction(Compost, Slurry))) +
  geom_col(position = "dodge") +
   geom_errorbar(position = position_dodge(0.9),width=0.4, alpha=0.9, linewidth=1.3, aes(ymin = emmean-SE, ymax = emmean+SE, group=interaction(Compost, Slurry),color=Compost))+
  geom_text(aes(y=emmean+SE, label=letters, color = Compost,hjust =-2,vjust=1), 
            size=5,position=position_dodge(.9))+
  scale_fill_manual(values=c("#EC7063","#B03A2E","#5DADE2","#21618C")) +
    scale_color_manual(values=c("#000","#000","#000","#000")) +
  scale_x_discrete(labels=c('Crossroads','Remembrance'))+
  labs(y="Distance to the Centroid")+
  theme(panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(size = 12, color = "black"),
        legend.position = "none", strip.text = element_text(size = 12, color = "black"), 
        axis.title = element_text(size = 12, color = "black"),
        axis.title.x = element_blank(),
        axis.text = element_text(size = 12, color = "black"));p.bac.beta
```

# Fungi 

```{r}
#####
#FUN_LAB
#################################################################
SAMPLE_DATA_LAB <- SAMPLE_DATA[SAMPLE_DATA$SOIL_SOURCE=="LAB",]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[!is.na(SAMPLE_DATA_LAB$Collection_Date),]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[SAMPLE_DATA_LAB$Collection_Date!="45777",]


#limits otu table to only samples used in compost study
OTU <- FUN_OTU[,colnames(FUN_OTU) %in% rownames(SAMPLE_DATA_LAB)]
#Removes OTUs absent from all relevant samples
OTU <- OTU[rowSums(OTU)> 1,]
#OTU <- OTU+1

OTU <- as.matrix(OTU)
TAX = FUN_TAX[rownames(OTU),]
samples = SAMPLE_DATA_LAB[colnames(OTU),]
sample_names(samples) <- samples$SEQUENCED_INV_NUMBER
rownames(samples) <- samples$SEQUENCED_INV_NUMBER
em_tse <- TreeSummarizedExperiment(assays = list(Count = OTU),
                                   rowData = TAX,
                                   colData = samples)
assayNames(em_tse) <- "counts" #Needed for prevalence filtering
# Extract count matrix and metadata
count_mat <- assay(em_tse, "counts")
coldata <- as.data.frame(colData(em_tse))

# Adonis - mary code
P.fun.fig3 <- convertToPhyloseq(em_tse,assay.type = "counts")
P.fun.fig3.rel = transform_sample_counts(P.fun.fig3, function(x) x / sum(x))
d <- data.frame(sample_data(P.fun.fig3))
data <- data.frame(t(otu_table(P.fun.fig3)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')

```

```{r}
# Beta dispersion
mod <- betadisper(dist, interaction(d$Slurry, d$Compost), type = c("centroid"),bias.adjust = F)
mod
par(mfrow=c(2,2))
plot(mod)
anova(mod)
plot(mod, ellipse = TRUE, hull = FALSE, conf = 0.90) # 90% data ellipse
(mod.HSD <- TukeyHSD(mod))
plot(mod.HSD)
boxplot(mod,
        xlab="Week")
print(mod, digits = max(3, getOption("digits") - 3),
                           neigen = 8)
df <- as.data.frame(mod$distances)
df$SEQUENCED_INV_NUMBER <- rownames(df)
names(df)[names(df) == "mod$distances"] <- "distance"



d.bd <- inner_join(df, d, by = "SEQUENCED_INV_NUMBER")


mod <- lm(distance ~ Slurry*Compost, data = d.bd) 
plot(mod)
Anova(mod, type = 3)
emmip(mod, Compost ~ Slurry, CIs = TRUE)
res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
plot(res[[1]], horizontal=F)
df <- as.data.frame(emmeans(mod, ~ Compost*Slurry))

res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  dplyr::select(., Compost, Slurry, .group)
df <- inner_join(df,groups, by = c('Compost', 'Slurry'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)


d.bd <- d.bd %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))

df <- df %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))

p <- ggplot() +
  geom_boxplot(data=d.bd, aes(x=Slurry, y=distance, fill = interaction(Compost, Slurry))) +
  labs(y="Distance to the Centroid")+
  theme_classic()+
  scale_color_manual(values = c("black", "black"),guide = "none")+
  scale_fill_manual(values = c("#EC7063","#B03A2E","#5DADE2","#21618C"),
                    labels=c('Crossroads No Compost', 'Crossroads With Compost', 'Remembrance No Compost', 'Remembrance With Compost')) +
  geom_text(data=df,stat='identity',
            aes(x=Slurry, y=emmean+SE+0.01, label=letters, color = Compost), 
            size=4,position=position_dodge(.9))+
  scale_x_discrete(labels = c("CROSS" = "Crossroads", "REM" = "Remembrance"))+
  theme(axis.text.x=element_text(colour = "black"),
        axis.text.y=element_text(colour = "black"),
        axis.title.x=element_blank(),
        legend.title = element_blank(),
        axis.line = element_line(colour = "black"));p
summarize(group_by(d.bd,Slurry, Compost),
          mean=mean(distance))

p.fun.beta <- ggplot(data=df,aes(x=Slurry, y=emmean, label=letters,fill = interaction(Compost, Slurry))) +
  geom_col(position = "dodge") +
  labs(y="Distance to the Centroid")+
  theme_classic()+  
   geom_errorbar(position = position_dodge(0.9),width=0.25,alpha=0.5, aes(ymin = emmean-SE, ymax = emmean+SE, group=interaction(Compost, Slurry),color=Compost))+
  scale_color_manual(values = c("black", "black"),guide = "none")+
  scale_fill_manual(values = c("#EC7063","#B03A2E","#5DADE2","#21618C"),
                    labels=c('Crossroads No Compost', 'Crossroads With Compost', 'Remembrance No Compost', 'Remembrance With Compost')) +
  geom_text(aes(y=emmean+SE, label=letters, color = Compost,hjust =-2,vjust=1), 
            size=4,position=position_dodge(.9))+
  scale_x_discrete(labels = c("CROSS" = "Crossroads", "REM" = "Remembrance"))+
  theme(axis.text.x=element_text(colour = "black"),
        axis.text.y=element_text(colour = "black"),
        axis.title.x=element_blank(),
        legend.title = element_blank(),
        legend.position="none",
        axis.line = element_line(colour = "black"));p.fun.beta
```


# Plot

```{r}

beta_dis_fig <- plot_grid(p.bac.beta,p.fun.beta, labels = c("A","B"));beta_dis_fig

ggsave(filename = "Data/output/Beta_Dispersion.svg", plot = beta_dis_fig,
       width = 10, height = 5, device = "svg")
```

