---
title: "Analysis for Figure 5"
author: "MD and EM"
date: "`r Sys.Date()`"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
   chunck_output_type: console
---


Inputs:

-   EJM-CLS-22F_pct98.csv
-   EJM-CLS-22B_pct98.csv
-   Sequencing_data_formatted_for_analysis(01.28.2026).xlsx
 

Outputs:

-   Figure 5

```{r, results = 'hide', message=FALSE}
knitr::opts_chunk$set(out.width = "100%")
library(tidyverse)
library(readxl)
library(mia)
library(phyloseq)
library(vegan)
library(car)
library(emmeans)
library(cowplot)
```


# Read in data 
```{r}
FUN <- read.csv("../Data/EJM-CLS-22F_pct98.csv")
BAC <- read.csv("../Data/EJM-CLS-22B_pct98.csv")
BAC <- BAC[!is.na(BAC$Kingdom),]
FUN <- FUN[FUN$Kingdom =="k__Fungi",]
FUN <- FUN[!is.na(FUN$Kingdom),]

SAMPLE_DATA <- as.data.frame(read_xlsx("../Data/Sequencing_data_formatted_for_analysis(01.28.2026).xlsx", sheet = "Soil_sample_info"))

rownames(FUN) <- FUN$X
FUN <- FUN[,-1]
rownames(BAC) <- BAC$X
BAC <- BAC[,-1]

BAC$Kingdom<-sub("^","k__",BAC$Kingdom)
BAC$Kingdom<-sub("k__NA",NA,BAC$Kingdom)
BAC$Phylum<-sub("^","p__",BAC$Phylum)
BAC$Phylum<-sub("p__NA",NA,BAC$Phylum)
BAC$Class<-sub("^","c__",BAC$Class)
BAC$Class<-sub("c__NA",NA,BAC$Class)
BAC$Order<-sub("^","o__",BAC$Order)
BAC$Order<-sub("o__NA",NA,BAC$Order)
BAC$Family<-sub("^","f__",BAC$Family)
BAC$Family<-sub("f__NA",NA,BAC$Family)
BAC$Genus<-sub("^","g__",BAC$Genus)
BAC$Genus<-sub("g__NA",NA,BAC$Genus)
BAC$Species<-sub("^","s__",BAC$Species)
BAC$Species<-sub("s__NA",NA,BAC$Species)

SAMPLE_DATA$EJM_SOIL_NUMBER <- as.factor(SAMPLE_DATA$EJM_SOIL_NUMBER)

FUN_OTU<- FUN[,8:length(colnames(FUN))]
FUN_TAX <- FUN[,1:7]
BAC_OTU<- BAC[,8:length(colnames(BAC))]
BAC_TAX <- BAC[,1:7]

BAC_OTU <- BAC_OTU[rowSums(BAC_OTU)>1,]
FUN_OTU <- FUN_OTU[rowSums(FUN_OTU)>1,]

BAC_OTU <- BAC_OTU[,colSums(BAC_OTU)>1000]
FUN_OTU <- FUN_OTU[,colSums(FUN_OTU)>1000]

colSums(BAC_OTU)

rownames(SAMPLE_DATA)<- SAMPLE_DATA$SEQUENCED_INV_NUMBER
```

# Bacteria 
## Generate phyloseq object
```{r}
SAMPLE_DATA_LAB <- SAMPLE_DATA[SAMPLE_DATA$SOIL_SOURCE=="LAB",]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[!is.na(SAMPLE_DATA_LAB$Collection_Date),]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[SAMPLE_DATA_LAB$Collection_Date!="45777",]


OTU <- BAC_OTU[,colnames(BAC_OTU) %in% rownames(SAMPLE_DATA_LAB)]
OTU <- OTU[rowSums(OTU)> 1,]
rowSums(OTU)

OTU <- as.matrix(OTU)
TAX = BAC_TAX[rownames(OTU),]
samples = SAMPLE_DATA_LAB[colnames(OTU),]
sample_names(samples) <- samples$SEQUENCED_INV_NUMBER
rownames(samples) <- samples$SEQUENCED_INV_NUMBER
em_tse <- TreeSummarizedExperiment(assays = list(Count = OTU),
                                   rowData = TAX,
                                   colData = samples)
assayNames(em_tse) <- "counts" #Needed for prevalence filtering

P.bac.count <- convertToPhyloseq(em_tse,assay.type = "counts")
P.bac.rel = transform_sample_counts(P.bac.count, function(x) x / sum(x))
d <- data.frame(sample_data(P.bac.rel))
data <- data.frame(t(otu_table(P.bac.rel)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')
```

## Beta dispersion model
```{r, warning = F, message = F}
mod <- betadisper(dist, interaction(d$Slurry, d$Compost), type = c("centroid"),bias.adjust = F)
mod
par(mfrow=c(1,1))
plot(mod)
anova(mod)
plot(mod, ellipse = TRUE, hull = FALSE, conf = 0.90) 
(mod.HSD <- TukeyHSD(mod))
plot(mod.HSD)
boxplot(mod)
print(mod, digits = max(3, getOption("digits") - 3), neigen = 8)

df <- as.data.frame(mod$distances)
df$SEQUENCED_INV_NUMBER <- rownames(df)
names(df)[names(df) == "mod$distances"] <- "distance"

d.bd <- dplyr::inner_join(df, d, by = "SEQUENCED_INV_NUMBER")

mod <- lm(distance ~ Slurry*Compost, data = d.bd) 
par(mfrow=c(2,2))
plot(mod)
Anova(mod, type = 3)
emmip(mod, Compost ~ Slurry, CIs = TRUE)
res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
plot(res[[1]], horizontal=F)
df <- as.data.frame(emmeans(mod, ~ Compost*Slurry))

res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  dplyr::select(., Compost, Slurry, .group)
df <- dplyr::inner_join(df,groups, by = c('Compost', 'Slurry'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)


d.bd <- d.bd %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))
```

## Make figure
```{r, warning = F, message = F}
p.bac.beta <- ggplot(data=df,aes(x=interaction(Compost, Slurry), y=emmean, label=letters,fill = interaction(Compost, Slurry))) +
geom_col(position = "dodge") +
 geom_errorbar(position = position_dodge(0.9),width=0.3, alpha=0.9, linewidth=0.7, aes(ymin = emmean-SE, ymax = emmean+SE, group=interaction(Compost, Slurry),color=Compost))+
  geom_text(aes(y=emmean+SE, label=letters, color = Compost,hjust =-2,vjust=0.5), 
            size=5,position=position_dodge(.9))+
  scale_fill_manual(values=c("#EC7063","#B03A2E","#5DADE2","#21618C")) +
    scale_color_manual(values=c("#000","#000","#000","#000")) +
  scale_x_discrete(labels=c('Crossroads\nNo Compost','Crossroads\nWith Compost','Remembrance\nNo Compost','Remembrance\nWith Compost'))+
  theme_classic()+
  labs(y="Distance to the Centroid")+
  theme(legend.position = "none",
        axis.title.x = element_blank());p.bac.beta
```

# Fungi 

## Make phyloseq object
```{r, warning = F, message = F}
SAMPLE_DATA_LAB <- SAMPLE_DATA[SAMPLE_DATA$SOIL_SOURCE=="LAB",]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[!is.na(SAMPLE_DATA_LAB$Collection_Date),]
SAMPLE_DATA_LAB <- SAMPLE_DATA_LAB[SAMPLE_DATA_LAB$Collection_Date!="45777",]

OTU <- FUN_OTU[,colnames(FUN_OTU) %in% rownames(SAMPLE_DATA_LAB)]
OTU <- OTU[rowSums(OTU)> 1,]
OTU <- as.matrix(OTU)
TAX = FUN_TAX[rownames(OTU),]
samples = SAMPLE_DATA_LAB[colnames(OTU),]
sample_names(samples) <- samples$SEQUENCED_INV_NUMBER
rownames(samples) <- samples$SEQUENCED_INV_NUMBER
em_tse <- TreeSummarizedExperiment(assays = list(Count = OTU),
                                   rowData = TAX,
                                   colData = samples)
assayNames(em_tse) <- "counts" 

P.fun.count <- convertToPhyloseq(em_tse,assay.type = "counts")
P.fun.rel = transform_sample_counts(P.fun.count, function(x) x / sum(x))

d <- data.frame(sample_data(P.fun.rel))
data <- data.frame(t(otu_table(P.fun.rel)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')

```

## Beta dispersion model

```{r, warning = F, message = F}
mod <- betadisper(dist, interaction(d$Slurry, d$Compost), type = c("centroid"),bias.adjust = F)
mod
par(mfrow=c(1,1))
plot(mod)
anova(mod)
plot(mod, ellipse = TRUE, hull = FALSE, conf = 0.90) 
(mod.HSD <- TukeyHSD(mod))
plot(mod.HSD)
boxplot(mod)
print(mod, digits = max(3, getOption("digits") - 3),  neigen = 8)
df <- as.data.frame(mod$distances)
df$SEQUENCED_INV_NUMBER <- rownames(df)
names(df)[names(df) == "mod$distances"] <- "distance"
d.bd <- dplyr::inner_join(df, d, by = "SEQUENCED_INV_NUMBER")


mod <- lm(distance ~ Slurry*Compost, data = d.bd) 
par(mfrow=c(2,2))
plot(mod)
Anova(mod, type = 3)
emmip(mod, Compost ~ Slurry, CIs = TRUE)
res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
plot(res[[1]], horizontal=F)
df <- as.data.frame(emmeans(mod, ~ Compost*Slurry))

res <- emmeans(mod, list(pairwise ~ Compost*Slurry), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  dplyr::select(., Compost, Slurry, .group)
df <- dplyr::inner_join(df,groups, by = c('Compost', 'Slurry'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)


d.bd <- d.bd %>%
mutate(Compost = as_factor(Compost)) %>%
mutate(Compost = fct_relevel(Compost, "NONE", "COMP"))
```

## Make figure
```{r, warning = F, message = F}
p.fun.beta <- ggplot(data=df,aes(x=interaction(Compost, Slurry), y=emmean, label=letters,fill = interaction(Compost, Slurry))) +
  geom_col(position = "dodge") +
   geom_errorbar(position = position_dodge(0.9),width=0.3, alpha=0.9, linewidth=0.7, aes(ymin = emmean-SE, ymax = emmean+SE, group=interaction(Compost, Slurry),color=Compost))+
  geom_text(aes(y=emmean+SE, label=letters, color = Compost,hjust =-2,vjust=1), 
            size=5,position=position_dodge(.9))+
  scale_fill_manual(values=c("#EC7063","#B03A2E","#5DADE2","#21618C")) +
    scale_color_manual(values=c("#000","#000","#000","#000")) +
  scale_x_discrete(labels=c('Crossroads\nNo Compost','Crossroads\nWith Compost','Remembrance\nNo Compost','Remembrance\nWith Compost'))+
  theme_classic()+
  theme(legend.position = "none",
        axis.title = element_blank());p.fun.beta
```


# Compile Plots

```{r, warning = F, message = F}
fig5 <- plot_grid(p.bac.beta,p.fun.beta, labels = c("A","B"));fig5

ggsave(filename = "../Data/output/Beta_Dispersion.svg", plot = fig5, width = 10, height = 5, device = "svg")
```

